repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-json
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        types_or: [ python, jupyter ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, jupyter ]
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        files: ^src/
        types: [python]
        additional_dependencies: ['pyright@1.1.294']
